### ISSUE TITLE
Insecure: use NativeApp.openURLInDefaultBrowser() instead

### ISSUE THREAD

**Issue by peterflynn** [catanghel/search-with-google#1]
Brackets-shell isn't safe for running unknown/untrusted web content -- it has some cross-domain protections turned off and exposes APIs that can modify the user's local files.  To open general web content like this, you can use NativeApp.openURLInDefaultBrowser() to open a new tab in Chrome/FF/Safari/etc. (whatever the user's main browser is).

We will be [blocking window.open() access soon](https://github.com/adobe/brackets/pull/8365) since it's easy to accidentally use insecurely, so to keep the extension working you'll need to make this change anyway.  There are still several weeks before the next release would ship, so hopefully it's not too much of a rush to make the change.  (And the NativeApp API will work in older versions of Brackets as well).

Thanks!

**Comment by catanghel** [comment]
Solved in version 0.2.1

**Comment by peterflynn** [comment]
Thanks for the quick fix!
