### ISSUE TITLE
Search on php.net and other sites

### ISSUE THREAD

**Issue by sQuarecoW** [catanghel/search-with-google#3]
I would like an extra option to search on php.net and maybe MDN or some other sites.

Maybe an options file that we can fill ourselves?

**Comment by catanghel** [comment]
Thank you for you request. 
I am currently working on a configurable extention and hopefully I will release an update soon. 
My intention is to give the user the possibility to choose from a predefined list of sites.

**Comment by sQuarecoW** [comment]
Super!

**Comment by catanghel** [comment]
Added php.net and MDN in version 0.3.0
You can add other sites by updating the sites.js but this is not the official (recommended) way to do it. 
I plan to have this in the user interface in future versions
